<?php
	/** @var \MvcCore\Ext\Controllers\DataGrids\View $this */
	/** @var \MvcCore\Ext\Controllers\DataGrid $grid */
	$gridCssClasses = $grid->GetCssClasses();
	$gridId = $grid->GetId();
	$nonceAttr = $this->nonce !== NULL 
		? ' nonce="' . $this->nonce . '"' 
		: '' ;
?><div id="<?php echo $gridId; ?>"<?php
	if (count($gridCssClasses) > 0) 
		echo ' class="'.implode(' ', $gridCssClasses) . '"';
?>></div>
<script<?php echo $nonceAttr; ?>>new <?php echo $jsClassFullName; ?>({
ElementSelector:'#<?php echo $gridId; ?>',
RenderConfig:<?php echo \MvcCore\Tool::JsonEncode($grid->GetConfigRendering()); ?>,
Columns:<?php echo \MvcCore\Tool::JsonEncode($grid->GetConfigColumns(FALSE)); ?>,
UrlSegments:<?php echo \MvcCore\Tool::JsonEncode($grid->GetConfigUrlSegments()); ?>,
DataUrl:'<?php echo $grid->GetDataUrl(); ?>',
RowSelection:<?php echo $grid->GetRowSelection(); ?>,
ItemsPerPage:<?php echo $grid->GetItemsPerPage(); ?>
},{
Data:<?php echo \MvcCore\Tool::JsonEncode($grid->GetPageData()); ?>,
TotalCount:<?php echo $grid->GetTotalCount(); ?>,
RowCount:<?php $rowCount = count($grid->GetPageData()); echo $rowCount; ?>,
StartRow:<?php echo $grid->GetOffset(); ?>,
EndRow:<?php echo $grid->GetOffset() + $rowCount; ?>
});</script>