<?php
	/** @var \MvcCore\Ext\Controllers\DataGrids\View $this */
	/** @var \MvcCore\Ext\Controllers\DataGrids\AgGrid $grid */
	$renderConf = $grid->GetConfigRendering();
	$themeCssClass = $renderConf->GetTheme();
	$gridCssClasses = $grid->GetCssClasses();
	$gridCssClasses[] = $themeCssClass;
	$renderBottomControls = (
		$renderConf->GetRenderControlStatus() || 
		$renderConf->GetRenderControlPaging() || 
		$renderConf->GetRenderControlCountScales()
	);
	$gridId = $grid->GetId();
	$nonceAttr = $this->nonce !== NULL 
		? ' nonce="' . $this->nonce . '"' 
		: '' ;
	if ($renderBottomControls)
		$gridCssClasses[] = 'grid-with-bottom-controls';
	$gridContClassAttr = count($gridCssClasses) > 0
		? ' class="'.implode(' ', $gridCssClasses) . '"'
		: '';
	$controlsWrapperCssClasses = $renderConf->GetCssClassesControlsWrapper();
	$controlsWrapperCssClass = count($controlsWrapperCssClasses) > 0
		? implode(' ', $controlsWrapperCssClasses)
		: '';
?><div id="<?php echo $gridId; ?>"<?php echo $gridContClassAttr; ?>>
	<div class="grid-table-component <?php echo $themeCssClass; ?>"></div>
	<?php if ($renderBottomControls): ?>
		<div class="<?php echo $controlsWrapperCssClass; ?> grid-controls-bottom"><?php 
			echo $this->RenderGridControlCountScales();
			echo $this->RenderGridControlStatus();
			echo $this->RenderGridControlPaging();
		?></div>
	<?php endif; ?>
</div>
<script<?php echo $nonceAttr; ?>>new <?php echo $grid->GetJsClassFullName(); ?>(<?php
	echo \MvcCore\Tool::JsonEncode([
		'contElementSelector'	=> '#' . $gridId,
		'renderConfig'			=> $renderConf,
		'columns'				=> $grid->GetConfigColumns(FALSE),
		'locales'				=> $grid->GetConfigLocales(),
		'urlSegments'			=> $grid->GetConfigUrlSegments(),
		'filterOperatorPrefixes'=> $grid->GetFilterOperatorPrefixes(),
		'ajaxParamsNames'		=> $grid->GetAjaxParamsNames(),
		'id'					=> $gridId,
		'clientPageMode'		=> $grid->GetClientPageMode(),
		'dataUrl'				=> $grid->GetDataUrl(),
		'columnsStatesUrl'		=> $grid->GetColumnsStatesUrl(),
		'columnsSizesUrl'		=> $grid->GetColumnsSizesUrl(),
		'dataRequestMethod'		=> $grid->GetDataRequestMethod(),
		'rowSelection'			=> $grid->GetRowSelection(),
		'itemsPerPage'			=> $grid->GetItemsPerPage(),
		'page'					=> $grid->GetPage(),
		'count'					=> $grid->GetCount(),
		'sortingMode'			=> $grid->GetSortingMode(),
		'filteringMode'			=> $grid->GetFilteringMode(),
		'controlsTexts'			=> $grid->GetControlsTexts(),
		'timeZoneOffset'		=> $grid->GetTimeZoneOffsetSeconds(),
		'clientRowBuffer'		=> $grid->GetClientRowBuffer(),
		'clientMaxRowsInCache'	=> $grid->GetClientMaxRowsInCache(),
		'clientRowBufferMax'	=> $grid::CLIENT_JS_BUFFER_MAX_SIZE,
	]);
?>,<?php
	echo \MvcCore\Tool::JsonEncode([
		'totalCount'		=> $grid->GetTotalCount(),
		'offset'			=> $grid->GetOffset(),
		'limit'				=> $grid->GetLimit(),
		'sorting'			=> $grid->GetAjaxSorting(),
		'filtering'			=> $grid->GetAjaxFiltering(),
		'url'				=> $this->controller->GetRequest()->GetFullUrl(),
		'path'				=> $grid->GetGridRequest()->GetPath(),
		'dataCount'			=> count($grid->GetPageData()),
		'data'				=> $grid->GetPageData()
	]);
?>);</script>