<?php

	/** @var \MvcCore\Ext\Controllers\DataGrids\View $this */
	/** @var \MvcCore\Ext\Controllers\DataGrids\AgGrid $grid */
	$renderConf = $grid->GetConfigRendering();
	$themeCssClass = $renderConf->GetTheme();
	$gridCssClasses = $grid->GetCssClasses();
	$gridCssClasses[] = $themeCssClass;
	$renderBottomControls = (
		$renderConf->GetRenderControlStatus() || 
		$renderConf->GetRenderControlPaging() || 
		$renderConf->GetRenderControlCountScales()
	);
	$renderTableHead = $renderConf->GetRenderTableHead();
	$renderTableHeadSorting = $renderTableHead && $renderConf->GetRenderTableHeadSorting();
	$renderTableHeadFiltering = $renderTableHead && $renderConf->GetRenderTableHeadFiltering();
	
	$gridCssClasses[] = $renderBottomControls 
		? 'grid-with-bottom-controls' 
		: 'grid-no-bottom-controls';
	$gridCssClasses[] = $renderTableHead 
		? 'grid-with-table-head' 
		: 'grid-no-table-head';
	$gridCssClasses[] = $renderTableHeadSorting 
		? 'grid-with-table-head-sorting' 
		: 'grid-no-table-head-sorting';
	$gridCssClasses[] = $renderTableHeadFiltering 
		? 'grid-with-table-head-filtering' 
		: 'grid-no-table-head-filtering';

	$gridId = $grid->GetId();
	$nonceAttr = $this->nonce !== NULL 
		? ' nonce="' . $this->nonce . '"' 
		: '' ;
	$gridContClassAttr = count($gridCssClasses) > 0
		? ' class="'.implode(' ', $gridCssClasses) . '"'
		: '';
	$controlsWrapperCssClasses = $renderConf->GetCssClassesControlsWrapper();
	$controlsWrapperCssClass = count($controlsWrapperCssClasses) > 0
		? implode(' ', $controlsWrapperCssClasses)
		: '';
?><div id="<?php echo $gridId; ?>"<?php echo $gridContClassAttr; ?>>
	<div class="grid-table-component <?php echo $themeCssClass; ?>"></div>
	<?php if ($renderBottomControls): ?>
		<div class="<?php echo $controlsWrapperCssClass; ?> grid-controls-bottom"><?php 
			echo $this->RenderGridControlCountScales();
			echo $this->RenderGridControlStatus();
			echo $this->RenderGridControlPaging();
		?></div>
	<?php endif; ?>
</div>
<script<?php echo $nonceAttr; ?>>new <?php echo $grid->GetJsClassFullName(); ?>(<?php
	echo \MvcCore\Tool::JsonEncode($grid->GetClientServerConfig());
?>,<?php
	echo \MvcCore\Tool::JsonEncode($grid->GetClientInitData());
?>);</script>