<?php
	/** @var \MvcCore\Ext\Controllers\DataGrids\View $this */
	/** @var \MvcCore\Ext\Controllers\DataGrid $grid */

	$renderConf = $this->GetConfigRendering();
	$cssClassesControl = $renderConf->GetCssClassesControlCountScales();
	$cssClassesCurrent = implode(' ', $renderConf->GetCssClassesControlCountScalesCurrent());
	$cssClassesButton = implode(' ', $renderConf->GetCssClassesControlCountScalesButton());
	$countScales = $grid->GetCountScales();
	$displayingCount = $grid->GetCount();
	$totalCount = $grid->GetTotalCount();
	$countScales2Render = [];
	foreach ($countScales as $countScale):
		if ($countScale !== 0 && $countScale > $totalCount) continue;
		$countScales2Render[$countScale] = $countScale === $displayingCount;
	endforeach;
	$countScales2RenderCount = count($countScales2Render);
	$firstIsCurrent = $countScales2RenderCount === 1 && $grid->GetPagesCount() === 1;
	$cssClassesControl[] = 'grid-control-items-count-' . $countScales2RenderCount;

?><table<?php
	if (count($cssClassesControl) > 0)
		echo ' class="' . implode(' ', $cssClassesControl) . '"';
?>><tbody><tr><?php
	foreach ($countScales2Render as $countScale => $current):
		$current = $current || $firstIsCurrent;
		?><td class="grid-count<?php
			if ($current) echo ' ' . $cssClassesCurrent;
		?>"><?php

			$text = ($countScale === 0)
				? $this->EscapeHtml($grid->GetControlText('all'))
				: (string) $countScale;

			if ($current):
				?><span class="<?php
				echo $cssClassesCurrent;
				?>"><?php
					echo $text;
				?></span><?php
			else:
				?><a class="<?php
					echo $cssClassesButton;
				?>" href="<?php
					echo $grid->GridCountUrl($countScale);
				?>"><span><b><?php
					echo $text;
				?></span></b></a><?php
			endif;

		?></td><?php
		
	endforeach;
?></tr></tbody></table>