<?php
	/** @var \MvcCore\Ext\Controllers\DataGrids\View $this */
	/** @var \MvcCore\Ext\Controllers\DataGrid $grid */
	/** @var \MvcCore\Ext\Controllers\DataGrids\Paging\Page[] $pagingItems */

	$pagingItems = $grid->GetPaging();
	$renderConf = $this->GetConfigRendering();
	$cssClassesControl = $renderConf->GetCssClassesControlPaging();
	$cssClassesButton = implode(' ', $renderConf->GetCssClassesControlPagingButton());
	$cssClassesCurrent = implode(' ', $renderConf->GetCssClassesControlPagingCurrent());
	$cssClassesControl[] = 'grid-control-items-count-' . count($pagingItems);

?><table<?php
	if (count($cssClassesControl) > 0)
		echo ' class="' . implode(' ', $cssClassesControl) . '"';
?>><tbody><?php
	foreach ($pagingItems as $pagingItem):
		
		?><td class="grid-page <?php
			echo $pagingItem->GetCssClass();
		?>"><?php

		if ($pagingItem instanceof \MvcCore\Ext\Controllers\DataGrids\Paging\Dot):
			?><span><?php echo $this->EscapeHtml($pagingItem->GetText()); ?></span><?php
		elseif ($pagingItem->IsCurrent()):
			?><span class="<?php echo $cssClassesCurrent; ?>"><?php
				echo $this->EscapeHtml($pagingItem->GetText());
			?></span><?php
		else:
			?><a class="<?php echo $cssClassesButton; ?>" href="<?php
				echo $pagingItem->GetUrl();
			?>" data-offset="<?php echo $pagingItem->GetOffset() ?>"><span><b><?php
				echo $this->EscapeHtml($pagingItem->GetText());
			?></b></span></a><?php
		endif;

		?></td><?php
		
	endforeach;
?></tr></table>